# container2/cloudbuild.yaml
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/kubernetes-repo/container2:${SHORT_SHA}', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/kubernetes-repo/container2:${SHORT_SHA}']
  
  # Deploy container image to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - 'set'
    - 'image'
    - 'deployment/container2'
    - 'container2=us-central1-docker.pkg.dev/${PROJECT_ID}/kubernetes-repo/container2:${SHORT_SHA}'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=kubernetes-assignment-cluster'

images:
- 'us-central1-docker.pkg.dev/${PROJECT_ID}/kubernetes-repo/container2:${SHORT_SHA}'