steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/kubernetes-repo/container2:latest', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/kubernetes-repo/container2:latest']
  
  # Set up kubectl and authenticate with GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'kubernetes-assignment-cluster'
      - '--zone'
      - 'us-central1-c'
    id: 'Set up kubectl'
  
  # Deploy using the YAML file from k8s folder
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'kubectl'
      - 'apply'
      - '-f'
      - 'k8s/deployment.yaml'
    id: 'Deploy container2 to GKE'

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/kubernetes-repo/container2:latest'
options:
  logging: CLOUD_LOGGING_ONLY