apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
        - name: container2
          image: us-central1-docker.pkg.dev/kubernetes-454319/kubernetes-repo/container2:latest
          ports:
            - containerPort: 3001
          env:
            - name: STORAGE_DIR
              value: "/Falgun_PV_dir"
            - name: PORT
              value: "3001"
          volumeMounts:
            - name: shared-data
              mountPath: /Falgun_PV_dir
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: falgun-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: container2